name: Test Github Actions
on:
  push:
  schedule:
    - cron: '0 0 1 * *'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Compile basic LaTeX document
        uses: ./
        with:
          root_file: test.tex
          working_directory: test/
      - name: Compile LaTeX document with biblatex/biber
        uses: ./
        with:
          root_file: biblatex.tex
          working_directory: test/
          extra_packages: biblatex-ieee
      - name: Check pdf file
        run: |
          set -e
          file test/test.pdf | grep -q ' PDF '
          file test/biblatex.pdf | grep -q ' PDF '
